---
title: "Représentation graphiques avec R"
subtitle: "Aperçu des différentes fonctionnalités de visualisation graphqiue"
img: images/entete.png
# date: 
author: Hugues Pecout (CNRS, UMR Géographie-Cités)
institute: "JA SO-MATE 2023, Limoges"
lang: fr
editor: source
format:
  revealjs: 
    template-partials:
      - title-slide.html
    theme: [dark, styles.scss]
    logo: images/logo_hp.png
    footer: "JA SO-MATE 2023 - Représentations graphiques avec R"
    scrollable: TRUE
    smaller: TRUE
    overview: TRUE
    chalkboard: FALSE
    transition: fade
    transition-speed: fast
    menu: TRUE
    css: style.css
    pointer:
      pointerSize: 20
      color: 'red4'
revealjs-plugins:
  - pointer
---

## De Excel à R


## Historique 

## 1995 - plot R-base

plot() et associée

## 2001 - Lattice

New API
Easy small multiples

## 2007 - ggplot2

Revolution...

## ggplot2 extensions

exts.ggplot2.tidyverse.org

## Customization et Art graphique

Cedric Scherer - X-Men Characters
Tania Shapiro - Best selling Authors


# Palettes de couleur


# Visualisation thématique

## Analyse de réseau

networkD3

## Analyse de séquence


## Scatterplot3D

## rgl

## heatmap

superheat
ComplexHeatmap

## Textuelle

wordcloud

## Slope graphs

CGPfunctions

## Circular plot

https://jokergoo.github.io/circlize_book/book/

## Survival

Survival plots

## Visualisation spatiale 

## Intéractivité (javascript link)

htmlwidgets.org

## leaflet

## rbokeh

## rCharts

## highcharter

## Shiny

## Autre (plotly et cie)

Plotly > ggplot2 > Plotly.js > D3.js > Javascript

echarts4r 

robservable

# Export

## Classique

## notebook

## shiny


# Ressource

## R graph galley

## R charts

## Rzine

## ggplot2 official

https://www.data-imaginist.com/screens/


